FROM openjdk
WORKDIR usr/lib
ADD ./target/UserAutheticationService-0.0.1-SNAPSHOT.jar /usr/lib/UserAutheticationService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","UserAutheticationService-0.0.1-SNAPSHOT.jar"]