server:
  port: 8086
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/favouriteMoviesDb
  application:
    name: user-favourite-movie-service
eureka:
   client:
     serviceUrl:
       defaultZone: http://localhost:8761/eureka
     fetchRegistry: true
     registerWithEureka: true
