version: '3.9'
services:
  mysqlservice:
    image: mysql:latest
    ports:
      - 3366:3306
    container_name: mysql-container
    network_mode: host
    hostname: localhost
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root


  mongodbservice:
    image: mongo
    container_name: mongo-container
    network_mode: host
    hostname: localhost
    ports:
      - 27017:27017

  userauthenticationservice:
    container_name: user-authentication-service
    build: UserAutheticationService/
    hostname: localhost
    network_mode: host
    ports:
      - 8084:8084
    depends_on:
      - mysqlservice
      - eurekaServer
      - cloudapiservice
    restart: always

  usermovieservice:
    container_name: user-movie-service
    build: MovieService/
    hostname: localhost
    network_mode: host
    ports:
      - 8081:8081
    depends_on:
      - mongodbservice
      - eurekaServer
      - cloudapiservice
    restart: always

  favouritemovieservice:
    container_name: favourite-movie-service
    build: FavouriteMovieService/
    hostname: localhost
    network_mode: host
    ports:
      - 8086:8086
    depends_on:
      - mongodbservice
      - eurekaServer
      - cloudapiservice
    restart: always

  cloudapiservice:
    image: cloud-api-service
    build: APIGateway/
    restart: always
    network_mode: host
    #hostname: localhost
    ports:
      - 9000:9000
    environment:
      API_GATEWAY_PORT: 9000
      EUREKA_SERVER_IP: localhost
      EUREKA_SERVER_PORT: 8761
    depends_on:
      - eurekaServer


  eurekaServer:
    image: eureka-service
    build: EurekaServer/
    restart: always
    network_mode: host
    #hostname: localhost
    environment:
      EUREKA_SERVER_PORT: 8761
    ports:
      - 8761:8761

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-container
    ports:
      - 5672:5672
      - 15672:15672
    network_mode: host
    restart: always